package cmd

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/hungnguyen18/uzp-cli/internal/envutil"
	"github.com/spf13/cobra"
)

var templateComments bool

var templateCmd = &cobra.Command{
	Use:   "template",
	Short: "Generate .env.example template from vault project keys",
	Long: `Generate Template

Generate a .env.example template from project keys (without secret values).

USAGE:
  uzp template --project PROJECT_NAME [--comments] [> output_file]

EXAMPLES:
  uzp template -p myapp                    Print template to stdout
  uzp template -p myapp > .env.example     Save template to file
  uzp template -p myapp --comments         Add comment hints based on key names

OUTPUT FORMAT:
  # Environment variables for project: myapp
  # Generated by uzp - Do NOT fill in real values
  # Use ` + "`" + `uzp inject -p myapp` + "`" + ` to get actual values
  API_KEY=
  DATABASE_URL=

NOTE:
  Keys are sorted alphabetically and converted to UPPERCASE with underscores.
  No secret values are included in the output.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Validate arguments FIRST - show help immediately if missing project
		if templateProjectName == "" {
			return fmt.Errorf("missing project name\n\nusage: uzp template -p PROJECT_NAME [--comments]\n\nSee 'uzp template --help' for examples")
		}

		// Check if vault is unlocked, prompt for password if needed
		if err := ensureVaultUnlocked(); err != nil {
			return err
		}

		// Get project secrets
		secrets, err := vault.GetProjectSecrets(templateProjectName)
		if err != nil {
			return fmt.Errorf("project not found: %s", templateProjectName)
		}

		if len(secrets) == 0 {
			fmt.Fprintf(os.Stderr, "No secrets found in project '%s'\n", templateProjectName)
			return nil
		}

		// Sort keys for consistent output
		keys := make([]string, 0, len(secrets))
		for key := range secrets {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		// Show success feedback to stderr (won't be redirected to file)
		fmt.Fprintf(os.Stderr, "Generating template for %d keys from project '%s'\n", len(secrets), templateProjectName)

		// Output header
		fmt.Printf("# Environment variables for project: %s\n", templateProjectName)
		fmt.Printf("# Generated by uzp - Do NOT fill in real values\n")
		fmt.Printf("# Use `uzp inject -p %s` to get actual values\n\n", templateProjectName)

		// Output keys without values
		for _, key := range keys {
			envKey := envutil.ConvertToEnvKey(key)
			if templateComments {
				comment := commentHintGenerate(envKey)
				fmt.Printf("%s=  # %s\n", envKey, comment)
			} else {
				fmt.Printf("%s=\n", envKey)
			}
		}

		// Success message to stderr
		fmt.Fprintf(os.Stderr, "Template generated successfully\n")

		return nil
	},
}

var templateProjectName string

func init() {
	templateCmd.Flags().StringVarP(&templateProjectName, "project", "p", "", "Project name to generate template from")
	templateCmd.Flags().BoolVar(&templateComments, "comments", false, "Add comment hints based on key name patterns")
}

// commentHintGenerate returns a type hint comment based on the env key name pattern.
func commentHintGenerate(envKey string) string {
	upper := strings.ToUpper(envKey)

	switch {
	case strings.HasSuffix(upper, "_URL") || strings.HasSuffix(upper, "_URI"):
		if strings.Contains(upper, "DATABASE") || strings.Contains(upper, "DB") || strings.Contains(upper, "POSTGRES") || strings.Contains(upper, "MYSQL") || strings.Contains(upper, "MONGO") || strings.Contains(upper, "REDIS") {
			return "Database connection URL"
		}
		if strings.Contains(upper, "API") {
			return "API endpoint URL"
		}
		if strings.Contains(upper, "WEBHOOK") {
			return "Webhook URL"
		}
		return "URL"

	case strings.Contains(upper, "API_KEY") || strings.Contains(upper, "APIKEY"):
		return "API key"

	case strings.Contains(upper, "SECRET_KEY") || strings.Contains(upper, "SECRET"):
		return "Secret key"

	case strings.Contains(upper, "TOKEN"):
		if strings.Contains(upper, "ACCESS") {
			return "Access token"
		}
		if strings.Contains(upper, "REFRESH") {
			return "Refresh token"
		}
		return "Authentication token"

	case strings.Contains(upper, "PASSWORD") || strings.Contains(upper, "PASSWD"):
		return "Password"

	case strings.HasSuffix(upper, "_PORT") || upper == "PORT":
		return "Port number"

	case strings.HasSuffix(upper, "_HOST") || upper == "HOST":
		return "Hostname"

	case strings.Contains(upper, "EMAIL"):
		return "Email address"

	case strings.Contains(upper, "REGION"):
		return "Region identifier"

	case strings.Contains(upper, "BUCKET"):
		return "Storage bucket name"

	case strings.Contains(upper, "KEY_ID") || strings.Contains(upper, "KEY"):
		return "Key"

	case strings.Contains(upper, "ENV") || strings.Contains(upper, "ENVIRONMENT"):
		return "Environment (e.g. development, staging, production)"

	case strings.Contains(upper, "DEBUG"):
		return "Debug flag (true/false)"

	case strings.Contains(upper, "LOG"):
		return "Log level or config"

	default:
		return "Configuration value"
	}
}
